[option]
exclude_paths = []

[rules]
case_default = false
enum_with_type = true
for_with_begin = true
function_same_as_system_function = false
function_with_automatic = true
generate_for_with_label = true
generate_if_with_label = false
generate_keyword = true
genvar_declaration = true
if_with_begin = true
inout_with_tri = false
input_with_var = false
interface_port_with_modport = false
legacy_always = true
level_sensitive_always = true
loop_variable_declaration = true
non_ansi_module = true
output_with_var = false
parameter_in_package = false
priority_keyword = false
tab_character = true
unique0_keyword = false
unique_keyword = false
wire_reg = false

