name: svlint

on: [push, pull_request]

jobs:
  svlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install svlint
        run: |
          sudo snap install svlint

      - name: Run svlint
        run: |
          svlint \
            -f rtl/common/compile.f \
            -f rtl/router/compile.f \
            -f rtl/fabric/compile.f \
            -f rtl/axi_adapter/compile.f
        env:
          TNOC_HOME: ${{ github.workspace }}

